In [3]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [4]:
dataset = pd.read_excel('fruit.xlsx')
dataset.head()

diameter  weight  red  green  blue    name
0      2.96   86.76  172     85     2  orange
1      3.91   88.05  166     78     3  orange
2      4.42   95.17  156     81     2  orange
3      4.47   95.60  163     81     4  orange
4      4.48   95.76  161     72     9  orange

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   diameter  10000 non-null  float64
 1   weight    10000 non-null  float64
 2   red       10000 non-null  int64  
 3   green     10000 non-null  int64  
 4   blue      10000 non-null  int64  
 5   name      10000 non-null  object 
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [6]:
dataset.empty

False

In [7]:
en = LabelEncoder()

dataset['name'] = en.fit_transform(dataset['name'])
dataset.head()

diameter  weight  red  green  blue  name
0      2.96   86.76  172     85     2     1
1      3.91   88.05  166     78     3     1
2      4.42   95.17  156     81     2     1
3      4.47   95.60  163     81     4     1
4      4.48   95.76  161     72     9     1

In [8]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
x

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])

In [10]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [11]:
x_train,x_test,y_train,y_test= train_test_split(x, y, test_size=0.2, random_state=123)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_train))


x_train =  8000
x_test =  2000
y_train =  8000
y_test =  8000


In [12]:
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [13]:
x_train

array([[ 1.40581808,  1.4183702 , -0.27199554,  1.19324519, -1.03227097],
       [ 0.69304398,  0.69950687,  0.39571226,  0.08064231,  0.39822925],
       [-1.35297665, -1.34325454,  0.77725958, -0.00494252,  0.06811382],
       ...,
       [-0.31201879, -0.3847701 ,  0.58648592, -0.34728187,  0.28819078],
       [-1.15811755, -1.16721335,  0.68187275,  1.10766035, -0.48207858],
       [-0.41457621, -0.40015234,  0.77725958,  1.87792388, -1.03227097]])

In [14]:
x_test

array([[-0.72224849, -0.7310414 , -1.03509018, -0.00494252, -1.03227097],
       [-1.63500957, -1.63175699,  0.68187275,  0.93649068, -0.81219401],
       [ 1.58529358,  1.5957787 ,  0.87264641, -0.77520605,  0.50826773],
       ...,
       [-0.64533042, -0.64729366,  1.1588069 ,  2.47701774, -0.70215553],
       [ 0.87764734,  0.89434857,  1.06342007, -2.0589786 , -1.03227097],
       [-1.52219641, -1.48682211,  1.82651471,  0.59415133, -0.04192466]])

In [15]:
y_train

array([0, 0, 1, ..., 0, 1, 1])

In [16]:
y_test

array([1, 1, 0, ..., 1, 0, 1])

In [17]:
 classifier = GaussianNB()
 classifier.fit(x_train,y_train)

GaussianNB()

In [18]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 0, ..., 1, 0, 1])

In [19]:
classifier.predict_proba(x_test)

array([[2.91609281e-03, 9.97083907e-01],
       [3.73045370e-07, 9.99999627e-01],
       [9.99997219e-01, 2.78115682e-06],
       ...,
       [5.50292701e-05, 9.99944971e-01],
       [9.99456947e-01, 5.43053358e-04],
       [1.58064364e-06, 9.99998419e-01]])

In [20]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[915  91]
 [ 66 928]]


In [21]:
akurasi = classification_report(y_test,y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      1006
           1       0.91      0.93      0.92       994

    accuracy                           0.92      2000
   macro avg       0.92      0.92      0.92      2000
weighted avg       0.92      0.92      0.92      2000



In [22]:
akurasi = accuracy_score(y_test,y_pred)
print("Tingkat Akurasi : %d persen"%(akurasi*100))

Tingkat Akurasi : 92 persen


In [23]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)
ydata

y_test  y_pred
0          1       1
1          1       1
2          0       0
3          1       1
4          1       1
...      ...     ...
1995       0       0
1996       0       0
1997       1       1
1998       0       0
1999       1       1

[2000 rows x 2 columns]

In [27]:
ydata.to_excel("dataactualpred.xlsx", index=False)